###
GET http://localhost:8080/songs

###
GET http://localhost:8080/songs/1

###
POST http://localhost:8080/songs
Content-Type: application/json

{
  "title": "Maria",
  "author": "Scooter"
}

###
PUT http://localhost:8080/songs/1
Content-Type: application/json

{
"title": "new",
"author": "Someone"
}

###
DELETE http://localhost:8080/songs/1
